### ISSUE TITLE
POSIX extension requirement?

### ISSUE THREAD

**Issue by arthurmv** [shish/shimmie2#710]
If I update from 2.6.2 with 2.8.1 I get a blank page, and with 2.7.0 I got this:
```
Fatal error: Uncaught Error: Call to undefined function posix_getpid() in W:\htdocs\shimmie\vendor\shish\eventtracer-php\src\EventTracer.php:66 Stack trace: #0 W:\htdocs\shimmie\vendor\shish\eventtracer-php\src\EventTracer.php(89): EventTracer->log_event('B', Array) #1 W:\htdocs\shimmie\core\_bootstrap.php(24): EventTracer->begin('Bootstrap') #2 W:\htdocs\shimmie\index.php(86): require_once('W:\\htdocs\\shimm...') #3 {main} thrown in W:\htdocs\shimmie\vendor\shish\eventtracer-php\src\EventTracer.php on line 66
```
The new version is not Windows compatible? I see something about POSIX.

**Comment by shish** [comment]
The POSIX dependency was added inadvertently, I'll put out a 2.7.1 with updated dependencies~

Not sure why 2.8.1 would be having issues though...

**Comment by arthurmv** [comment]
I got these lines on browser console updating to 2.8.1
```
Unchecked runtime.lastError: The message port closed before a response was received.
DevTools failed to parse SourceMap: chrome-extension://bbcinlkgjjkejfdpemiealijmmooekmp/sourcemaps/onloadwff.js.map
DevTools failed to parse SourceMap: chrome-extension://gmgoamodcdcjnbaobigkjelfplakmdhh/include.preload.js.map
DevTools failed to parse SourceMap: chrome-extension://gmgoamodcdcjnbaobigkjelfplakmdhh/include.postload.js.map
```
I don't know if it is important or not. What can I do?

**Comment by shish** [comment]
`chrome-extension://` is your browser plugins, not shimmie ^^

**Comment by arthurmv** [comment]
The blank page is there on another browsers... I think could be this line
`Unchecked runtime.lastError: The message port closed before a response was received.`
or maybe something else...

**Comment by shish** [comment]
I've never seen that error before; google suggests that it is also something to do with a browser extension...

Is there anything in the web server error logs?

**Comment by arthurmv** [comment]
This time I didn't replace the files, just copy the `data\config`  folder and 2.8.1 works but when I try to enter to any entry (picture) I got this...
```
Fatal error: Uncaught TypeError: exif_read_data() expects parameter 2 to be string, int given in W:\htdocs\shimmie\ext\handle_pixel\theme.php:12 Stack trace: #0 W:\htdocs\shimmie\ext\handle_pixel\theme.php(12): exif_read_data('data\\images\\b7\\...', 0, true) #1 W:\htdocs\shimmie\core\extension.php(388): PixelFileHandlerTheme->display_image(Object(Page), Object(Image)) #2 W:\htdocs\shimmie\core\send_event.php(113): DataHandlerExtension->onDisplayingImage(Object(DisplayingImageEvent)) #3 W:\htdocs\shimmie\ext\view\main.php(63): send_event(Object(DisplayingImageEvent)) #4 W:\htdocs\shimmie\core\send_event.php(113): ViewImage->onPageRequest(Object(PageRequestEvent)) #5 W:\htdocs\shimmie\index.php(95): send_event(Object(PageRequestEvent)) #6 {main} thrown in W:\htdocs\shimmie\ext\handle_pixel\theme.php on line 12
```

**Comment by arthurmv** [comment]
This time I didn't replace the files, just copy the `data\config`  folder to the shimmie 2.8.1 and it works but when I try to enter to any entry (picture) I got this...
```
Fatal error: Uncaught TypeError: exif_read_data() expects parameter 2 to be string, int given in W:\htdocs\shimmie\ext\handle_pixel\theme.php:12 Stack trace: #0 W:\htdocs\shimmie\ext\handle_pixel\theme.php(12): exif_read_data('data\\images\\b7\\...', 0, true) #1 W:\htdocs\shimmie\core\extension.php(388): PixelFileHandlerTheme->display_image(Object(Page), Object(Image)) #2 W:\htdocs\shimmie\core\send_event.php(113): DataHandlerExtension->onDisplayingImage(Object(DisplayingImageEvent)) #3 W:\htdocs\shimmie\ext\view\main.php(63): send_event(Object(DisplayingImageEvent)) #4 W:\htdocs\shimmie\core\send_event.php(113): ViewImage->onPageRequest(Object(PageRequestEvent)) #5 W:\htdocs\shimmie\index.php(95): send_event(Object(PageRequestEvent)) #6 {main} thrown in W:\htdocs\shimmie\ext\handle_pixel\theme.php on line 12
```

**Comment by arthurmv** [comment]
This time I didn't replace the files, just copy the `data\config`  folder to shimmie 2.8.1 and it works but when I try to enter to any entry (picture) I got this...
```
Fatal error: Uncaught TypeError: exif_read_data() expects parameter 2 to be string, int given in W:\htdocs\shimmie\ext\handle_pixel\theme.php:12 Stack trace: #0 W:\htdocs\shimmie\ext\handle_pixel\theme.php(12): exif_read_data('data\\images\\b7\\...', 0, true) #1 W:\htdocs\shimmie\core\extension.php(388): PixelFileHandlerTheme->display_image(Object(Page), Object(Image)) #2 W:\htdocs\shimmie\core\send_event.php(113): DataHandlerExtension->onDisplayingImage(Object(DisplayingImageEvent)) #3 W:\htdocs\shimmie\ext\view\main.php(63): send_event(Object(DisplayingImageEvent)) #4 W:\htdocs\shimmie\core\send_event.php(113): ViewImage->onPageRequest(Object(PageRequestEvent)) #5 W:\htdocs\shimmie\index.php(95): send_event(Object(PageRequestEvent)) #6 {main} thrown in W:\htdocs\shimmie\ext\handle_pixel\theme.php on line 12
```

**Comment by shish** [comment]
Ack, edee8e74 should fix that

**Comment by arthurmv** [comment]
This fix the issue. Updated to 2.8.2 and working.
Thanks a lot!
