### ISSUE TITLE
Replace image issue

### ISSUE THREAD

**Issue by arthurmv** [shish/shimmie2#718]
```
Fatal error: Uncaught TypeError: Argument 1 passed to Image::by_id() must be of the type int, string given,
called in W:\htdocs\shimmie\ext\image\main.php on line 66
and defined in W:\htdocs\shimmie\core\imageboard\image.php:100
Stack trace:
#0 W:\htdocs\shimmie\ext\image\main.php(66): Image::by_id('13466')
#1 W:\htdocs\shimmie\core\send_event.php(113): ImageIO->onPageRequest(Object(PageRequestEvent))
#2 W:\htdocs\shimmie\index.php(95): send_event(Object(PageRequestEvent))
#3 {main} thrown in W:\htdocs\shimmie\core\imageboard\image.php on line 100
```
Happens after click `Replace` button.
_Shimmie version 2.8.3+_

**Comment by shish** [comment]
Should be fixed by 7871016, thanks for reporting :)

**Comment by arthurmv** [comment]
With 7871016 I got the replacement form but after click `Post` this happens:
```
Fatal error: Uncaught TypeError: Argument 1 passed to int_escape() must be of the type string or null, int given, called in D:\WEB\htdocs\shimmie\core\extension.php on line 305 and defined in D:\WEB\htdocs\shimmie\core\polyfills.php:448 Stack trace: #0 D:\WEB\htdocs\shimmie\core\extension.php(305): int_escape(13485) #1 D:\WEB\htdocs\shimmie\core\send_event.php(113): DataHandlerExtension->onDataUpload(Object(DataUploadEvent)) #2 D:\WEB\htdocs\shimmie\ext\upload\main.php(368): send_event(Object(DataUploadEvent)) #3 D:\WEB\htdocs\shimmie\ext\upload\main.php(220): Upload->try_upload(Array, Array, NULL, 13485) #4 D:\WEB\htdocs\shimmie\core\send_event.php(113): Upload->onPageRequest(Object(PageRequestEvent)) #5 D:\WEB\htdocs\shimmie\index.php(95): send_event(Object(PageRequestEvent)) #6 {main} thrown in D:\WEB\htdocs\shimmie\core\polyfills.php on line 448
```

**Comment by shish** [comment]
Sorry for the delay, I ended up going though all the image replace code and doing a bunch of refactoring - hopefully 72645af9 should fix your issue and a few others ^^

**Comment by arthurmv** [comment]
Oh nice! 72645af fix the issue. Thanks again! You're awesome!
