### ISSUE TITLE
Uncaught Error: Typed property Image::$width must not be accessed before initialization

### ISSUE THREAD

**Issue by PronMaster** [shish/shimmie2#861]
**Server Software**
(You can get all these stats from `http://<your site>/system_info`)

 - Shimmie version: 2.91
 - Database: mysql
 - Web server: Apache

**Client Software (please complete the following information)**
 - Device: Windows
 - Browser: Chrome

**What steps trigger this bug**
1. When trying to upload any video
2. N/A
3. N/A

**What did you expect to happen?**
Maybe a fix?

**What actually happened?**
Getting a error when trying to upload videos after updating to 2.91 error log says this:

PHP Fatal error:  Uncaught Error: Typed property Image::$width must not be accessed before initialization in /home/xxx/public_html/ext/handle_video/main.php:87
Stack trace:
#0 /home/xxx/public_html/core/extension.php(399): VideoFileHandler->media_check_properties(Object(MediaCheckPropertiesEvent))
#1 /home/xxx/public_html/core/send_event.php(113): DataHandlerExtension->onMediaCheckProperties(Object(MediaCheckPropertiesEvent))
#2 /home/xxx/public_html/core/extension.php(341): send_event(Object(MediaCheckPropertiesEvent))
#3 /home/xxx/public_html/core/send_event.php(113): DataHandlerExtension->onDataUpload(Object(DataUploadEvent))
#4 /home/xxx/public_html/ext/upload/main.php(355): send_event(Object(DataUploadEvent))
#5 /home/xxx/public_html/ext/upload/main.php(236): Upload->try_upload(Array, Array, NULL)
#6 /home/xxx/public_html/core/send_event.php(113): Upload->onPageRequest(Object(PageRequestEvent))
#7 /home/xxx/public_html/index.php(82): send_event(Object(PageRequestEvent))
#8 {mai in /home/xxx/public_html/ext/handle_video/main.php on line 87

**Comment by PronMaster** [comment]
Fixed!!
