### ISSUE TITLE
Video MIME types not supported (video/mp4; video/x-matroska)

### ISSUE THREAD

**Issue by Taijefx34** [shish/shimmie2#867]
**Server Software**

 - Shimmie version: 2.9.1 (Release)
 - PHP 8.0
 - Database: sqlite
 - Web server: apache (not sure, its this repo)
 - WSL (1)

**Client Software**
 - Device: Windows 10 Pro
 - Browser: Chrome

**What steps trigger this bug**
1. Go to Upload Page
2. Click on Choose File
3. Select any .mp4 video file
4. Click on Post

**What did you expect to happen?**
I expected a video to be posted.

**What actually happened?**
MIME type not supported: video/mp4

Same with .mkv (and ig any others video types)
MIME type not supported: video/x-matroska

**Comment by shish** [comment]
Do you have the Handle Video extension enabled?

**Comment by Taijefx34** [comment]
> Do you have the Handle Video extension enabled?

Sorry, but where i can find it?

**Comment by shish** [comment]
While logged in as an admin, User Links -> Extension Manager -> Tick the box

**Comment by Taijefx34** [comment]
Oh, thanks :)
It was disabled

**Comment by Taijefx34** [comment]
Hmm, sttill cant upload
Let me show an error

**Comment by Taijefx34** [comment]
```
[Sat Jan 15 20:46:04 2022] 127.0.0.1:57842 Accepted
[Sat Jan 15 20:46:04 2022] 127.0.0.1:57843 Accepted
[Sat Jan 15 20:46:05 2022] PHP Fatal error:  Uncaught Error: Typed property Image::$width must not be accessed before initialization in /mnt/c/Users/Taijefx34/bubuntu/shimmie2/ext/handle_video/main.php:87
Stack trace:
#0 /mnt/c/Users/Taijefx34/bubuntu/shimmie2/core/extension.php(399): VideoFileHandler->media_check_properties()
#1 /mnt/c/Users/Taijefx34/bubuntu/shimmie2/core/send_event.php(113): DataHandlerExtension->onMediaCheckProperties()
#2 /mnt/c/Users/Taijefx34/bubuntu/shimmie2/core/extension.php(341): send_event()
#3 /mnt/c/Users/Taijefx34/bubuntu/shimmie2/core/send_event.php(113): DataHandlerExtension->onDataUpload()
#4 /mnt/c/Users/Taijefx34/bubuntu/shimmie2/ext/upload/main.php(355): send_event()
#5 /mnt/c/Users/Taijefx34/bubuntu/shimmie2/ext/upload/main.php(236): Upload->try_upload()
#6 /mnt/c/Users/Taijefx34/bubuntu/shimmie2/core/send_event.php(113): Upload->onPageRequest()
#7 /mnt/c/Users/Taijefx34/bubuntu/shimmie2/index.php(82): send_event()
#8 {main}
  thrown in /mnt/c/Users/Taijefx34/bubuntu/shimmie2/ext/handle_video/main.php on line 87
[Sat Jan 15 20:46:05 2022] 127.0.0.1:57842 [500]: POST /index.php?q=upload - Uncaught Error: Typed property Image::$width must not be accessed before initialization in /mnt/c/Users/Taijefx34/bubuntu/shimmie2/ext/handle_video/main.php:87
Stack trace:
#0 /mnt/c/Users/Taijefx34/bubuntu/shimmie2/core/extension.php(399): VideoFileHandler->media_check_properties()
#1 /mnt/c/Users/Taijefx34/bubuntu/shimmie2/core/send_event.php(113): DataHandlerExtension->onMediaCheckProperties()
#2 /mnt/c/Users/Taijefx34/bubuntu/shimmie2/core/extension.php(341): send_event()
#3 /mnt/c/Users/Taijefx34/bubuntu/shimmie2/core/send_event.php(113): DataHandlerExtension->onDataUpload()
#4 /mnt/c/Users/Taijefx34/bubuntu/shimmie2/ext/upload/main.php(355): send_event()
#5 /mnt/c/Users/Taijefx34/bubuntu/shimmie2/ext/upload/main.php(236): Upload->try_upload()
#6 /mnt/c/Users/Taijefx34/bubuntu/shimmie2/core/send_event.php(113): Upload->onPageRequest()
#7 /mnt/c/Users/Taijefx34/bubuntu/shimmie2/index.php(82): send_event()
#8 {main}
  thrown in /mnt/c/Users/Taijefx34/bubuntu/shimmie2/ext/handle_video/main.php on line 87
[Sat Jan 15 20:46:05 2022] 127.0.0.1:57842 Closing
[Sat Jan 15 20:46:05 2022] 127.0.0.1:57844 Accepted
[Sat Jan 15 20:46:06 2022] 127.0.0.1:57844 Closed without sending a request; it was probably just an unused speculative preconnection
[Sat Jan 15 20:46:06 2022] 127.0.0.1:57844 Closing
[Sat Jan 15 20:46:06 2022] 127.0.0.1:57843 Closed without sending a request; it was probably just an unused speculative preconnection
[Sat Jan 15 20:46:06 2022] 127.0.0.1:57843 Closing

```

**Comment by shish** [comment]
Gah, I think that's fixed in the latest git master branch, it is probably time for a new released version >.<

**Comment by Taijefx34** [comment]
Oh, ok.
Anyway, thank you)
Keep working, such a nice imageboard, Thank you a lot for this.

**Comment by Taijefx34** [comment]
My bad. Handle Video extension disabled.
